### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### get products
GET http://localhost:8090/api/v1/products

### items
GET http://localhost:8090/api/v1/items/6