server:
  port: ${APP_PORT:0}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: msvc-products
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:db_cloud}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_APP_HOST:localhost}:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.value}