create table if not exists products
(
    id        bigint generated by default as identity primary key,
    create_at date,
    name      varchar(255),
    price     double precision
    );

insert into products values (1, '12/10/2025', 'TV Sonic', 500.45);
insert into products values (2, '12/11/2025', 'TV Samsung', 600.45);
insert into products values (3, '12/12/2025', 'TV Cadmium', 700.45);
insert into products values (4, '12/01/2025', 'TV Panasonic', 800.45);
insert into products values (5, '12/02/2025', 'TV Challenger', 900.45);
insert into products values (6, '12/03/2025', 'TV Treat', 1000.45);