services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_cloud
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - spring

networks:
  spring:
    name: spring
    driver: bridge
volumes:
  db:
    name: postgres_data