server:
  servlet:
    context-path: /api/v1
  port: ${APP_PORT:9002}
spring:
  application:
    name: msvc-items

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_APP_HOST:localhost}:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 6
        failureRateThreshold: 50
        wait-duration-in-open-state: 20s
        permittedNumberOfCallsInHalfOpenState: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      getItemById:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 4s
    instances:
      getItemById:
        base-config: default

app:
  load-balancer:
    products: http://${PRODUCTS_APP_HOST:msvc-products}/api/v1/products
  feign:
    products:
      name: ${PRODUCTS_NAME:msvc-products}
      url: http://localhost:9000/api/v1/products