server:
  port: ${APP_PORT:8090}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_APP_HOST:localhost}:8761/eureka/

spring:
  application:
    name: msvc-gateway-server
  cloud:
    gateway:
      routes:
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            - Path=/api/v1/products/**
#            - Header=token, 12345
#            - Method=GET, POST
#            - Query=color
#            - Cookie=color, blue
          filters:
            - StripPrefix=0
            - SampleCookie=Hello from SampleCookie, user, Andres
        #            - name: SampleCookie
        #              args:
        #                message: Hello from SampleCookie
        #                name: user
        #                value: Andres
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/v1/items/**
          filters:
            - StripPrefix=0
            - AddRequestHeader=Authorization,Bearer ${JWT_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDI}
            - AddResponseHeader=Authorization,Bearer ${JWT_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDI}
            - AddRequestParameter=name, Andres
            - SetResponseHeader=Content-Type, text/plain
logging:
  level:
    web: DEBUG
    spring: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG